version: "3.9"

networks:
  db-net:
    driver: bridge
services:
  postgres_db:
    image: postgres
    restart: always
    command: postgres
    env_file:
      .env
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    expose:
      - $POSTGRES_PORT
    volumes:
      - ./docker/dbdata:/var/lib/POSTGRES/
    networks:
      - db-net

  # tn-nest:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   env_file:
  #     .env
  #   ports:
  #     - $APP_PORT:$APP_PORT
  #   networks:
  #     - db-net
  #   depends_on:
  #     - postgres_db

  parser:
    build:
      context: ./parser
      dockerfile: Dockerfile
    container_name: streamers-parser
    restart: always
    ports: 
      - $PARSER_PORT:$PARSER_PORT
    depends_on:
      - postgres_db
    networks:
      - db-net
